filebeat.inputs:
- type: log
  enabled: true
  multiline.type: pattern
  multiline.pattern: '^[[:space:]]Event:'
  multiline.negate: false
  multiline.match: after
  paths:
    - <IS-HOME>/repository/logs/wso2carbon.log

output.logstash:
  hosts: ["localhost:5044"]

